import type { Recipe } from './RecipeTypes';

export const mockRecipes: Recipe[] = [
  {
    id: 1,
    title: "Chicken Tikka Masala",
    description:
      "Creamy and flavorful Indian curry with tender chicken pieces in a rich tomato-based sauce",
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    cuisine: "Indian",
    cookTime: 45,
    servings: 4,
    rating: 4.8,
    difficulty: "Medium",
    dietaryRestrictions: ["Gluten-Free"],
    ingredients: [
      "2 lbs chicken breast, cubed",
      "1 cup plain yogurt",
      "2 cans diced tomatoes",
      "1 cup heavy cream",
      "2 tbsp garam masala",
      "1 tbsp turmeric",
      "2 tsp cumin",
      "1 onion, diced",
      "4 cloves garlic, minced",
      "1 inch ginger, grated",
    ],
    instructions: [
      "Marinate chicken in yogurt and spices for 2 hours",
      "Cook onion, garlic, and ginger until fragrant",
      "Add tomatoes and simmer for 10 minutes",
      "Add marinated chicken and cook until done",
      "Stir in cream and simmer for 5 minutes",
      "Serve with rice or naan",
    ],
    calories: 420,
    prepTime: 20,
  },
  {
    id: 2,
    title: "Mediterranean Quinoa Bowl",
    description:
      "Fresh and healthy quinoa bowl with Mediterranean vegetables, feta cheese, and lemon dressing",
    image: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400",
    cuisine: "Mediterranean",
    cookTime: 25,
    servings: 2,
    rating: 4.6,
    difficulty: "Easy",
    dietaryRestrictions: ["Vegetarian", "Gluten-Free"],
    ingredients: [
      "1 cup quinoa",
      "1/2 cup feta cheese",
      "1 cucumber, diced",
      "2 tomatoes, diced",
      "1/4 cup kalamata olives",
      "1/4 red onion, sliced",
      "2 tbsp olive oil",
      "1 lemon, juiced",
      "1 tsp oregano",
    ],
    instructions: [
      "Cook quinoa according to package directions",
      "Dice vegetables and crumble feta",
      "Whisk together olive oil, lemon juice, and oregano",
      "Combine quinoa with vegetables and feta",
      "Drizzle with dressing and toss",
      "Serve chilled or at room temperature",
    ],
    calories: 350,
    prepTime: 15,
  },
  {
    id: 3,
    title: "Korean Beef Bulgogi",
    description:
      "Sweet and savory Korean marinated beef, perfect with steamed rice and kimchi",
    image: "https://images.unsplash.com/photo-1553163147-622ab57be1c7?w=400",
    cuisine: "Korean",
    cookTime: 20,
    servings: 4,
    rating: 4.9,
    difficulty: "Easy",
    dietaryRestrictions: [],
    ingredients: [
      "2 lbs beef sirloin, thinly sliced",
      "1/2 cup soy sauce",
      "1 Asian pear, grated",
      "6 cloves garlic, minced",
      "2 tbsp sesame oil",
      "2 tbsp brown sugar",
      "1 tbsp rice wine",
      "1 tsp black pepper",
      "2 green onions, sliced",
    ],
    instructions: [
      "Combine all marinade ingredients",
      "Marinate sliced beef for at least 2 hours",
      "Heat pan or grill to high heat",
      "Cook beef in batches for 2-3 minutes per side",
      "Garnish with green onions",
      "Serve with steamed rice",
    ],
    calories: 380,
    prepTime: 180,
  },
  {
    id: 4,
    title: "Vegan Buddha Bowl",
    description:
      "Nutritious plant-based bowl with roasted vegetables, chickpeas, and tahini dressing",
    image: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38?w=400",
    cuisine: "Fusion",
    cookTime: 35,
    servings: 2,
    rating: 4.4,
    difficulty: "Easy",
    dietaryRestrictions: ["Vegan", "Gluten-Free"],
    ingredients: [
      "1 sweet potato, cubed",
      "1 can chickpeas, drained",
      "2 cups kale, chopped",
      "1/2 cup quinoa",
      "1/4 cup tahini",
      "2 tbsp lemon juice",
      "1 tbsp maple syrup",
      "1 clove garlic, minced",
      "2 tbsp olive oil",
    ],
    instructions: [
      "Roast sweet potato at 400°F for 25 minutes",
      "Cook quinoa according to package directions",
      "Massage kale with olive oil and lemon",
      "Whisk tahini dressing ingredients",
      "Assemble bowl with quinoa, vegetables, and chickpeas",
      "Drizzle with tahini dressing",
    ],
    calories: 420,
    prepTime: 15,
  },
  {
    id: 5,
    title: "Italian Carbonara",
    description:
      "Classic Roman pasta dish with eggs, cheese, pancetta, and black pepper",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc353d2e5?w=400",
    cuisine: "Italian",
    cookTime: 20,
    servings: 4,
    rating: 4.7,
    difficulty: "Medium",
    dietaryRestrictions: [],
    ingredients: [
      "1 lb spaghetti",
      "4 large eggs",
      "4 oz pancetta, diced",
      "1 cup Parmesan cheese, grated",
      "1 tsp black pepper",
      "Salt to taste",
      "2 cloves garlic, minced",
    ],
    instructions: [
      "Cook pasta in salted water until al dente",
      "Fry pancetta until crispy",
      "Whisk eggs with Parmesan and pepper",
      "Reserve pasta water, then drain pasta",
      "Toss hot pasta with pancetta and garlic",
      "Remove from heat and mix in egg mixture",
      "Add pasta water if needed for creaminess",
    ],
    calories: 520,
    prepTime: 10,
  },
  {
    id: 6,
    title: "Thai Green Curry",
    description:
      "Aromatic and spicy Thai curry with coconut milk, vegetables, and fresh herbs",
    image: "https://images.unsplash.com/photo-1455619452474-d2be8b1e70cd?w=400",
    cuisine: "Thai",
    cookTime: 30,
    servings: 4,
    rating: 4.5,
    difficulty: "Medium",
    dietaryRestrictions: ["Gluten-Free"],
    ingredients: [
      "3 tbsp green curry paste",
      "1 can coconut milk",
      "1 lb chicken thighs, sliced",
      "1 Thai eggplant, cubed",
      "1/4 cup Thai basil",
      "2 tbsp fish sauce",
      "1 tbsp palm sugar",
      "2 kaffir lime leaves",
      "1 red chili, sliced",
    ],
    instructions: [
      "Heat curry paste in a pan until fragrant",
      "Add thick coconut milk and cook until oil separates",
      "Add chicken and cook until nearly done",
      "Add remaining coconut milk and vegetables",
      "Season with fish sauce and palm sugar",
      "Garnish with basil and lime leaves",
    ],
    calories: 390,
    prepTime: 20,
  },
  {
    id: 7,
    title: "Classic Beef Tacos",
    description:
      "Traditional Mexican tacos with seasoned ground beef and fresh toppings",
    image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ca4b?w=400",
    cuisine: "Mexican",
    cookTime: 25,
    servings: 4,
    rating: 4.3,
    difficulty: "Easy",
    dietaryRestrictions: [],
    ingredients: [
      "1 lb ground beef",
      "8 taco shells",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 tbsp chili powder",
      "1 tsp cumin",
      "1/2 cup shredded cheese",
      "1 tomato, diced",
      "1 cup lettuce, shredded",
      "1/4 cup sour cream",
    ],
    instructions: [
      "Brown ground beef with onion and garlic",
      "Add spices and cook for 2 minutes",
      "Simmer with 1/4 cup water for 5 minutes",
      "Warm taco shells according to package",
      "Fill shells with beef mixture",
      "Top with cheese, tomato, lettuce, and sour cream",
    ],
    calories: 350,
    prepTime: 15,
  },
  {
    id: 8,
    title: "Japanese Chicken Teriyaki",
    description:
      "Glazed chicken with homemade teriyaki sauce served over steamed rice",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
    cuisine: "Japanese",
    cookTime: 30,
    servings: 4,
    rating: 4.6,
    difficulty: "Easy",
    dietaryRestrictions: [],
    ingredients: [
      "4 chicken breasts",
      "1/4 cup soy sauce",
      "2 tbsp mirin",
      "2 tbsp sake",
      "3 tbsp sugar",
      "1 tbsp cornstarch",
      "2 tbsp vegetable oil",
      "2 green onions, sliced",
      "1 tsp sesame seeds",
    ],
    instructions: [
      "Season chicken and cook in oil until golden",
      "Remove chicken and set aside",
      "Combine teriyaki sauce ingredients",
      "Cook sauce until thickened",
      "Return chicken to pan and glaze",
      "Garnish with green onions and sesame seeds",
    ],
    calories: 310,
    prepTime: 10,
  },
];

export const initialFilters = {
  searchTerm: "",
  selectedCuisine: "",
  selectedDietary: "",
  maxCookTime: "",
  sortBy: "rating",
};

export const initialState = {
  recipes: mockRecipes,
  filteredRecipes: mockRecipes,
  filters: initialFilters,
  selectedRecipe: null,
  favoriteRecipes: [],
  isLoading: false,
};
